version: "2"
services:
  app:
    build: .
    ports:
      - "8080:80"
      - "4043:443"
    volumes:
      - $PWD:/app
      - ./development.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
      - phpmyadmin

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: lamp
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: lamp_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
